name: Build & Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
  registry_name: ghcr.io
  image_name: adb2cgroupsmembership

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - id: docker-tag
      uses: yuya-takeyama/docker-tag-from-github-ref-action@v1
    - name: Docker Login
      # You may pin to the exact commit or the version.
      uses: docker/login-action@v2.0.0
      with:
        registry: ${{ env.registry_name }}
        username:  ${{ github.actor }}
        password:  ${{ secrets.GITHUB_TOKEN }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        # list of Docker images to use as base name for tags
        images: |
          ${{ env.registry_name }}/${{ github.repository_owner }}/${{ env.image_name }}
        # generate Docker tags based on the following events/attributes
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
        flavor: |
          latest=true
    - name: Build and push
      # You may pin to the exact commit or the version.
      uses: docker/build-push-action@v3.0.0
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: src/
        # Push is a shorthand for --output=type=registry
        push: true
        build-args: | 
          BUILD_VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          GITHUB_RUN_NUMBER=${{ github.run_number }}
        tags: 
          ${{ steps.meta.outputs.tags }}
      
